name: ask_me2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-143.0.dev <4.0.0'

dependencies:
  cached_network_image: null
  cloud_firestore: null
  cupertino_icons: null
  firebase_auth: null
  firebase_core: null
  firebase_storage: null
  cloud_functions:
  file_picker:
  video_player:
  rxdart:
  flutter:
    sdk: flutter
  get_storage: null
  google_fonts: null
  image_picker: null
  advance_pdf_viewer2:
  intl: null
  provider: null
  http: 
  connectivity_plus:
  flutter_offline:
  mailer: ^6.0.1

dev_dependencies:
  flutter_lints: null
  flutter_launcher_icons:
  connectivity:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ask_me_icon.png"
  web:
    generate: true
    image_path: "assets/ask_me_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/health.jpeg
    - assets/mechanic.jpeg
    - assets/religion.jpeg
    - assets/social.jpeg
    - assets/tech.jpeg
    - assets/fixing.jpeg
  