name: ask_me2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-143.0.dev <4.0.0'

dependencies:
  cloud_firestore: null
  cupertino_icons: null
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  get_storage: 
  image_picker: null
  intl: null
  provider: null

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
