// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCseJ7rSFWEqN8UrNZ7Wr41DDG6G3-Aogo',
    appId: '1:110393023133:web:826fe1af242e4e1e77d274',
    messagingSenderId: '110393023133',
    projectId: 'ask-me-75670',
    authDomain: 'ask-me-75670.firebaseapp.com',
    storageBucket: 'ask-me-75670.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgoX-z8o-yHB11jADgLnpxJEjdHC-X80s',
    appId: '1:110393023133:android:af673386829a0b2e77d274',
    messagingSenderId: '110393023133',
    projectId: 'ask-me-75670',
    storageBucket: 'ask-me-75670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2MVJ4uVw_h2ED58lNOgz9oIAoyc-xSU',
    appId: '1:110393023133:ios:ce7a2cff8f381eaf77d274',
    messagingSenderId: '110393023133',
    projectId: 'ask-me-75670',
    storageBucket: 'ask-me-75670.appspot.com',
    iosBundleId: 'com.example.askMe2',
  );
}
